import { minimatch } from "minimatch";

export function compileExcludes(globs: string[]): (rel: string) => boolean {
  return (rel: string) => globs.some((g) => minimatch(rel, g, { dot: true, matchBase: true }));
}

export function gitignoreLines(globs: string[]): string {
  return ["# generated by openclaw-gh-sync", ...globs].join("\n") + "\n";
}
